### ISSUE TITLE
[PE-D][Tester E] bug(feature): Sort Function is not optimized

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-F12-2/tp#146]
![image.png](https://raw.githubusercontent.com/midnightfeverrr/ped/main/files/04aaf63b-e36a-4779-90ac-83f0be53006b.png)

Why not make one sort command for better user experience, and create a parameter for `sort by`.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: midnightfeverrr/ped#8

**Comment by albertarielw** [comment]
fixed
